### ISSUE TITLE
Tutorials are scheduled in the final week of the term

### ISSUE THREAD

**Issue by MackDing** [ran123123123/Template#5]
We can all meet at my office after the lecture.

**Comment by ran123123123** [comment]
> We can all meet at my office after the lecture.

The celebrated theory is still the source of great controversy.

**Comment by MackDing** [comment]
> > We can all meet at my office after the lecture.
> 
> The celebrated theory is still the source of great controversy.


- I thought a good architectural structure should be useful, durable and beautiful.
